name: "Tests: E2E"
on: [pull_request]
jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: install dependencies
        run: npm ci
        working-directory: gha
      - name: install playwright browsers
        run: npx playwright install --with-deps
        working-directory: gha
      - name: npm run tests
        run: npm run tests
        working-directory: gha
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report/
          working-directory: gha
